---

stages:
  - test
  - publish

before_script:
  - python -m pip install -e .

Test against python2.7:
  tags:
    - python2.7
  script:
    - python -m pip install -r requirements-tests.txt
    - py.test tests/ --cov git_resolutions --flake8 --cov-report term-missing
  except:
    - rr-cache

Test against python3.5:
  tags:
    - python3.5
  script:
    - python -m pip install -r requirements-tests.txt
    - py.test tests/ --cov git_resolutions --flake8 --cov-report term-missing
  except:
    - rr-cache

Build executable:
  stage: publish
  tags:
    - python3.5
  script:
    - python -m zipapp src -p "/usr/bin/env python" -m "git_resolutions:main" -o git-resolutions
    - chmod +x git-resolutions
  artifacts:
    paths:
      - git-resolutions
  only:
    - master
    - publish
